name: depth_matching
channels:
  # - https://dx-mirrors.sensetime.com/anaconda/cloud/pytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - pytorch=1.13
  - pip
  - pip:
      - -r requirements.txt
